const rows = [
    {
      id: 4,
      username: 'visitor9',
      fullname: 'Visitor 9',
      email: 'visitor9@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 12,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor8',
      fullname: 'Visitor 8',
      email: 'visitor8@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 11,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor7',
      fullname: 'Visitor 7',
      email: 'visitor7@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 10,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor6',
      fullname: 'Visitor 6',
      email: 'visitor6@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 9,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor5',
      fullname: 'Visitor 5',
      email: 'visitor5@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 8,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor4',
      fullname: 'Visitor 4',
      email: 'visitor4@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 7,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor3',
      fullname: 'Visitor 3',
      email: 'visitor3@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 6,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor2',
      fullname: 'Visitor 2',
      email: 'visitor2@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 5,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor12',
      fullname: 'Visitor 12',
      email: 'visitor12@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 15,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor11',
      fullname: 'Visitor 11',
      email: 'visitor11@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 14,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor10',
      fullname: 'Visitor 10',
      email: 'visitor10@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 13,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 4,
      username: 'visitor1',
      fullname: 'Visitor 1',
      email: 'visitor1@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 4,
      role_id: 4,
      name: 'VISITOR'
    },
    {
      id: 2,
      username: 'modfus',
      fullname: 'Mod Fus',
      email: 'mod@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 2,
      role_id: 2,
      name: 'MODERATOR'
    },
    {
      id: 3,
      username: 'authorfus',
      fullname: 'Author Fus',
      email: 'author@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 3,
      role_id: 3,
      name: 'AUTHOR'
    },
    {
      id: 1,
      username: 'adminfus',
      fullname: 'Admin Fus',
      email: 'admin@gmail.com',
      password: '$2a$10$t1WDiR5YTs8lpJXnwlsuTOBfchMPxm4voeE4FVknM/dmQE0vPxvM2',
      city: null,
      avatar: 'https://mpng.subpng.com/20180810/tz/kisspng-shiba-inu-dogecoin-clip-art-scalable-vector-graphi-doge-pixel-www-pixshark-com-images-galleries-wit-5b6d30af29d5d9.5368936015338825431714.jpg',
      age: null,
      status: 'AVAILABLE',
      deleted: 0,
      deleted_at: null,
      user_id: 1,
      role_id: 1,
      name: 'ADMIN'
    }
];

const arr = rows.map(row => row);

// for (let i = rows.length - 1; i >= 0; i--) {
//     if (!obj[rows[i].user_id]) {
//         obj[rows[i].user_id] = {
//             ...rows[i],
//             roles: [rows[i].name]
//         };
//     } else {
//         obj[rows[i].user_id].roles.push(rows[i].name);
//     }
// }


console.log(rows.reverse());
// console.log(Object.values(obj));